config/routes.rb
CuppleHub::Application.routes.draw do


  resources :emails, :only => 'create'

  match "/thanks", to: 'home#thanks', as: 'thanks'
  get "profile/show"

  # match "/welcome", to: 'home#splash', as: 'welcome'
  # match "/profile", to: 'home#profile', as: 'profile'
  # get "front/index"
  # get 'home/get_couple'
  # get "modal/index"
  # get "home/modal1"

  resources :outings
  match "/questions", to: 'home#show', as: 'questions'

  devise_for :couples
  resources :couples do
    resources :user_likes
  end

  root to: 'home#splash'
end

app/models/couple.rb
class Couple < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :his_name, :her_name
  # attr_accessible :title, :body
  has_one :user_like, :dependent => :destroy
  accepts_nested_attributes_for :user_like

  def couple_names
    "#{self.her_name} & #{self.his_name}"
  end
end

app/controllers/couples_controller.rb
class CouplesController < ApplicationController
  def index
    @couples = Couple.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @couples }
    end
  end

  def show
    @couple = Couple.find(params[:id])
  end

  def new
    @couple = Couple.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @couple }
    end
  end

  def edit
    @couple = Couple.find(params[:id])

    respond_to do |format|
      if @couple.save
        format.html { redirect_to @couple, notice: 'Check out your matches!' }
        format.json { render json: @couple, status: :created, location: @couple }
      else
        format.html { render action: "new" }
        format.json { render json: @couple.errors, status: :unprocessable_entity }
      end
    end
  end

  def create
    @couple = Couple.new(params[:couple])

    respond_to do |format|
      if @couple.save
        format.html { redirect_to couples_path, notice: 'Check out your matches!' }
        format.json { render json: @couple, status: :created, location: @couple }
      else
        format.html { render action: "new" }
        format.json { render json: @couple.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @couple = Couple.find(params[:id])

    respond_to do |format|
      if @couple.update_attributes(params[:couple])
        format.html { redirect_to couples_path, notice: 'Nice update, maybe you have new matches!' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @couple.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @couple = Couple.find(params[:id])
    @couple.destroy

    respond_to do |format|
      format.html { redirect_to couples_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/couple_helper.rb
module CoupleHelper
end

app/views/couples/_form.html.erb
<%= form_for(@couple) do |f| %>
  <% if @couple.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@couple.errors.count, "error") %> prohibited this couple from being saved:</h2>

      <ul>
      <% @couple.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :her_name %><br />
    <%= f.text_field :her_name %>
  </div>
  <div class="field">
    <%= f.label :his_name %><br />
    <%= f.text_field :his_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/couples/_show.html.erb
<ul>
  <li>
    <%= @couple.couple_names %>
  </li>
  <li>
    <%= @couple.username %>
  </li>
  <li>
    <%= @couple.email %>
  </li>
</ul>

app/views/couples/edit.html.erb
<h1>Editing Couple</h1>

<%= render 'form' %>

<%= link_to 'Show', @couple %> |
<%= link_to 'Back', couples_path %>

app/views/couples/index.html.erb
<h1>Listing couples</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Email</th>
    <th>Her Name</th>
    <th>His Name</th>
    <th></th>
    <th></th>
  </tr>

<% @couples.each do |couple| %>
  <tr>
    <td><%= couple.username %></td>
    <td><%= couple.email %></td>
    <td><%= couple.her_name %></td>
    <td><%= couple.his_name %></td>
    <td></td>
    <td><%= link_to 'Show', couple %></td>
    <td><%= link_to 'Edit', edit_couple_path(couple) %></td>
    <td><%= link_to 'Destroy', couple, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New couple', new_couple_path %>

app/views/couples/new.html.erb
<h1>New Couple</h1>

<%= render 'form' %>

<%= link_to 'Back', couples_path %>

app/views/couples/show.html.erb
<ul>
  <li>
    <%= @couple.couple_names %>
  </li>
  <li>
    <%= @couple.username %>
  </li>
  <li>
    <%= @couple.email %>
  </li>
</ul>