config/routes.rb
CuppleHub::Application.routes.draw do


  resources :emails, :only => 'create'

  match "/thanks", to: 'home#thanks', as: 'thanks'
  get "profile/show"

  # match "/welcome", to: 'home#splash', as: 'welcome'
  # match "/profile", to: 'home#profile', as: 'profile'
  # get "front/index"
  # get 'home/get_couple'
  # get "modal/index"
  # get "home/modal1"

  resources :outings
  match "/questions", to: 'home#show', as: 'questions'

  devise_for :couples
  resources :couples do
    resources :user_likes
  end

  root to: 'home#splash'
end

app/models/outing.rb
class Outing < ActiveRecord::Base
  attr_accessible :address, :lat, :long, :name, :price
end

app/controllers/outings_controller.rb
class OutingsController < ApplicationController
  def index
    @outings = Outing.all
  end
  def show
    @outing = Outing.find(params[:id])
  end
  def edit
    @outing = Outing.find(params[:id])
  end
  def new
    @outing = Outing.new
  end
  def create
    @outing = Outing.new(params[:outing])

    respond_to do |format|
      if @outing.save
        format.html { redirect_to @outing, notice: 'outing was successfully created.' }
        format.json { render json: @outing, status: :created, location: @outing }
      else
        format.html { render action: "new" }
        format.json { render json: @outing.errors, status: :unprocessable_entity }
      end
    end
  end
  def update
    @outing = Outing.find(params[:id])

    respond_to do |format|
      if @outing.update_attributes(params[:outing])
        format.html { redirect_to @outing, notice: 'outing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @outing.errors, status: :unprocessable_entity }
      end
    end
  end
  def delete
    @outing = Outing.find(params[:id])
    @outing.destroy

    respond_to do |format|
      format.html { redirect_to outings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/outings_helper.rb
module OutingsHelper
end

app/views/outings/_form.html.erb
<%= form_for(@outing) do |f| %>
  <% if @outing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@outing.errors.count, "error") %> prohibited this outing from being saved:</h2>

      <ul>
      <% @outing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.number_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/outings/edit.html.erb
<h1>Editing Outing</h1>

<%= render 'form' %>

<%= link_to 'Show', @outing %> |
<%= link_to 'Back', outings_path %>

app/views/outings/index.html.erb
<h1>Listing outings</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @outings.each do |outing| %>
  <tr>
    <td><%= outing.name %></td>
    <td><%= outing.address %></td>
    <td><%= outing.price %></td>
    <td><%= link_to 'Show', outing %></td>
    <td><%= link_to 'Edit', edit_outing_path(outing) %></td>
    <td><%= link_to 'Destroy', outing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Outing', new_outing_path %>

app/views/outings/new.html.erb
<h1>New Outing</h1>

<%= render 'form' %>

<%= link_to 'Back', outings_path %>

app/views/outings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @outing.name %>
</p>

<p>
  <b>Address:</b>
  <%= @outing.address %>
</p>

<p>
  <b>Price:</b>
  <%= @outing.price %>
</p>


<%= link_to 'Edit', edit_outing_path(@outing) %> |
<%= link_to 'Back', outings_path %>