config/routes.rb
CuppleHub::Application.routes.draw do


  resources :emails, :only => 'create'

  match "/thanks", to: 'home#thanks', as: 'thanks'
  get "profile/show"

  # match "/welcome", to: 'home#splash', as: 'welcome'
  # match "/profile", to: 'home#profile', as: 'profile'
  # get "front/index"
  # get 'home/get_couple'
  # get "modal/index"
  # get "home/modal1"

  resources :outings
  match "/questions", to: 'home#show', as: 'questions'

  devise_for :couples
  resources :couples do
    resources :user_likes
  end

  root to: 'home#splash'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def show
  end
  def modal1
  end
  def splash
    @email = Email.new
  end
  def profile
    respond_to do |format|
      format.html
      format.js {render :couple_data}
    end
  end
  def thanks
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def resource_name
    :couple
  end
 
  def resource
     @resource  ||= Couple.new
  end
 
  def devise_mapping
     @devise_mapping  ||= Devise.mappings[:couple]
  end
end

app/views/home/_show.html.erb
<div class="loadin">
<div>
  <h2>Jaycee</h2>
  <h5>Jason & Kaycee</h5>
</div>
<p>26 & 28</p>
<p>Likes entertainment, food, culture.</p>
<%= link_to "suggest outing", "/profile/show" %>
</div>

app/views/home/couple_data.js.erb
$( ".info" ).html( '<%= j render :partial => 'show' %>'  );

app/views/home/index.html.erb
<h1>Welcome to CuppleHub</h1>

<%= form_for("couple", :url => couple_session_path) do |f| %>
  <div>
    <%= f.label :email %>
    <br>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :password %>
    <br>
    <%= f.password_field :password %>
  </div>
  <%= f.submit 'Sign in' %>
  <%#= link_to "Forgot your password?", new_password_path('couple') %>
<% end %>

<%= render "/devise/shared/links" %>

app/views/home/modal1.html.erb
<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Modal header</h3>
  </div>
  <div class="modal-body">
  
      <ul>
        <li>
					<%= image_tag("http://placehold.it/250x250&text=Food") %>
        </li>
        <li>
					<%= image_tag("http://placehold.it/250x250&text=Outdoors") %>
        </li>
        <li>
					<%= image_tag("http://placehold.it/250x250&text=Outdoors") %>
        </li>
      </ul>  
  
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <button class="btn btn-primary">Save changes</button>
  </div>
</div>

app/views/home/profile.html.erb
<div class="info">
  <h4>Here are the most compatible couples. See what they're all about and invite them for an outing!</h4>
</div>

<div id="profile menu">

  <%= link_to(image_tag('1.jpg'), profile_path, :id => 'centerbutton') %>

  <ul class="circles">
    <li><%= link_to image_tag('2.jpg'), :action => 'profile', :remote => true %></li>
    <li><a href="" title=""><%= image_tag '3.jpg' %></a></li>
    <li><a href="" title=""><%= image_tag '4.jpg' %></a></li>
    <li><a href="" title=""><%= image_tag '5.JPG' %></a></li>
    <li><a href="" title=""><%= image_tag 'couple.jpg' %></a></li>
    <li><a href="" title=""><%= image_tag 'Couple2.jpg' %></a></li>
  </ul>

</div><!--End Menu-->

app/views/home/show.html.erb
<!-- Modal 1 -->
<div id="modal1" class="modal fade hide" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Which Would You Prefer?  (1 of 8)</h3>
  </div>
  <div class="modal-body">
      <ul>
        <li>
					<%= image_tag("profiles/movie.jpg", class: "modal-image1") %>
        </li>
        <li>
					<%= image_tag("profiles/concert.jpg", class: "modal-image1") %>
        </li>
        <li>
					<%= image_tag("profiles/board_games.jpg", class: "modal-image1") %>
        </li>
      </ul>  
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Skip</button>
    <!--<button class="btn btn-primary">Save changes</button>-->
  </div>
</div>

<!-- Modal 2 -->
<div id="modal2" class="modal fade hide" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Food: What would you prefer? (2 of 8)</h3>
  </div>
  <div class="modal-body">
      <ul>
        <li>
					<%= image_tag("profiles/veg.jpg", class: "modal-image2") %>
        </li>
        <li>
					<%= image_tag("profiles/ethnic.jpg", class: "modal-image2") %>
        </li>
        <li>
					<%= image_tag("profiles/american.jpg", class: "modal-image2") %>
        </li>
      </ul>  
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Skip</button>
    <!--<button class="btn btn-primary">Save changes</button>-->
  </div>
</div>

<!-- Modal 3 -->
<div id="modal3" class="modal fade hide" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Drinks: What would you prefer? (3 of 8)</h3>
  </div>
  <div class="modal-body">
      <ul>
        <li>
					<%= image_tag("profiles/wine.jpg", class: "modal-image3") %>
        </li>
        <li>
					<%= image_tag("profiles/beer.jpg", class: "modal-image3") %>
        </li>
        <li>
					<%= image_tag("profiles/soda.jpg", class: "modal-image3") %>
        </li>
      </ul>  
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Skip</button>
    <!--<button class="btn btn-primary">Save changes</button>-->
  </div>
</div>

<!-- Modal 4 -->
<div id="modal4" class="modal fade hide" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Nightlife: Would You Rather Go.... (4 of 8) </h3>
  </div>
  <div class="modal-body">
      <ul>
        <li>
					<%= image_tag("profiles/dancing.jpg", class: "modal-image4") %>
        </li>
        <li>
					<%= image_tag("profiles/lounge.jpg", class: "modal-image4") %>
        </li>
        <li>
					<%= image_tag("profiles/pub.jpg", class: "modal-image4") %>
        </li>
      </ul>  
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Skip</button>
    <!--<button class="btn btn-primary">Save changes</button>-->
  </div>
</div>

<!-- Modal 5 -->
<div id="modal5" class="modal fade hide" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Athletics: What would you prefer? (5 of 8)</h3>
  </div>
  <div class="modal-body">
      <ul>
        <li>
					<%= image_tag("profiles/hiking.jpg", class: "modal-image5") %>
        </li>
        <li>
					<%= image_tag("profiles/dodgeball.jpg", class: "modal-image5") %>
        </li>
        <li>
					<%= image_tag("profiles/yoga.jpg", class: "modal-image5") %>
        </li>
      </ul>  
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Skip</button>
    <!--<button class="btn btn-primary">Save changes</button>-->
  </div>
</div>


<!-- Modal 6 -->
<div id="modal6" class="modal fade hide" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Travel: What would you prefer? (6 of 8)</h3>
  </div>
  <div class="modal-body">
      <ul>
        <li>
					<%= image_tag("profiles/outdoor.jpg", class: "modal-image6") %>
        </li>
        <li>
					<%= image_tag("profiles/roadtrip.jpg", class: "modal-image6") %>
        </li>
        <li>
					<%= image_tag("profiles/farmers_market.jpg", class: "modal-image6") %>
        </li>
      </ul>  
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Skip</button>
    <!--<button class="btn btn-primary">Save changes</button>-->
  </div>
</div>

<!-- Modal 7 -->
<div id="modal7" class="modal fade hide" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Culture: What would you prefer? (7 of 8)</h3>
  </div>
  <div class="modal-body">
      <ul>
        <li>
					<%= image_tag("profiles/broadway.jpg", class: "modal-image7") %>
        </li>
        <li>
					<%= image_tag("profiles/comedy.jpg", class: "modal-image7") %>
        </li>
        <li>
					<%= image_tag("profiles/museums.jpg", class: "modal-image7") %>
        </li>
      </ul>  
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Skip</button>
    <!--<button class="btn btn-primary">Save changes</button>-->
  </div>
</div>

<!-- Modal 8 -->
<div id="modal8" class="modal fade hide" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">One last step. Please fill your profile below. (8 of 8) </h3>
  </div>
  <div class="modal-body">
      <h3>Profile Information goes here, Form will come here</h3> 
      <!-- START FORM -->
      <form class="form-horizontal" action="/profile" method="post">
				<div class="control-group">
					<label class="control-label" for="inputEmail">Email</label>
					<div class="controls">
						<input type="text" id="inputEmail" placeholder="Email" value="damone@damonefrankline.com">
					</div>
				</div>
				<div class="control-group">
					<label class="control-label" for="inputPassword">Password</label>
					<div class="controls">
						<input type="password" id="inputPassword" placeholder="Password" value="password">
					</div>
				</div>

				<div class="control-group">
					<label class="control-label" for="inputName">Your Name</label>
					<div class="controls">
						<input type="text" id="inputName" placeholder="Your Full Name" value="Damone Franklin">
					</div>
				</div>
				<div class="control-group">
					<label class="control-label" for="inputPartnerName">Partner Name</label>
					<div class="controls">
						<input type="text" id="inputPartnerName" placeholder="Your Partner's Name Name" value="Annet">
					</div>
				</div>
				<div class="control-group">
					<label class="control-label" for="inputAge">Age</label>
					<div class="controls">
						<input type="text" id="inputAge" placeholder="Age" value="24">
					</div>
				</div>
				<div class="control-group">
					<label class="control-label" for="inputAddress">Enter your Address</label>
					<div class="controls">
						<textarea rows="3" id="inputName">Brooklyn, New york</textarea>
					</div>
				</div>
				<div class="control-group">
					<label class="control-label" for="inputPic">Profie Picture</label>
					<div class="controls">
						<input type="file">
					</div>
				</div>
				<div class="control-group">
					<div class="controls">
						<button type="submit" class="btn btn-primary">Submit</button>
					</div>
				</div>
			</form>
      <!-- END FORM -->
  </div>
  <div class="modal-footer">
    <!--<button class="btn" data-dismiss="modal" aria-hidden="true">Skip</button>-->
    <!--<button class="btn btn-primary">Save changes</button>-->
  </div>
</div>



<!-- Old page-->
<!--<h1>Questionaire</h1>
<!-- Button to trigger modal
<a href="#myModal" role="button" class="btn modal-btn" data-toggle="modal">Click to answer some questions</a>-->
<h2>The way couples connect with other couples</h2>
<div class="splash">
  <%= form_tag(questions_path) do  %>
    <div>
      <%= label_tag :email do %>
        <%= text_field_tag :email, nil, autofocus: true, placeholder: "Enter your email to get started!" %>
      <% end %>
      <%= submit_tag 'Go!', :class => "button" %>
    </div>
  <% end %>  
</div>
 
 


<script type="text/javascript">

$('body').modalmanager('loading');
      setTimeout(function(){
		    $("#modal1").modal({ width: '750px'
		    });
		  }, 500);


$('.modal-btn').on('click', function() {
      //alert($(this).text());
      $('body').modalmanager('loading');
      
      setTimeout(function(){
		    $("#modal1").modal({ width: '750px'
		    });
		  }, 500);
      
    });
<% (1..7).each do |i| %>
$(".modal-image<%= i %>").on('click', function() {
      //alert($(this).text());
      $("#modal<%= i %>").modal("hide");
      $('body').modalmanager('loading');
      
      setTimeout(function(){
		    $("#modal<%= i + 1 %>").modal({ width: '750px'
		    });
		  }, 500);
      
    });
    
<% end %>
$(".modal-image8").on('click', function() {
      //alert($(this).text());
      $("#modal8").modal("hide");
      $('body').modalmanager('loading');
      /* Redirect to main page */
      
    });
</script>

<style type="text/css">
	.modal, .modal.fade.in {
    top: 40% !important; /* was 10% */
	}

  
  ul {
    list-style: none;
    text-align: center;
  }
  ul li {
    margin: 5px;
    display: inline-block;
  }
  
  .modal-header {
  	color:brown;
  }
  .modal-header h3 {
  	color:brown;
  }
  
  .form-horizontal .control-label {
  	color: black;
  }
  
  img {
  	width:200px;
  	height: 200px;
  }
</style>

app/views/home/splash.html.erb
<h2>The way couples connect with other couples</h2>
<!-- <div class="splash">
  <%#= form_tag(questions_path) do  %>
    <div>
      <%#= label_tag :email do %>
        <%#= text_field_tag :email, nil, method: :get,autofocus: true, placeholder: "Enter your email to get started!" %>
      <%# end %>
      <%#= submit_tag 'Go!', :class => "button" %>
    </div>
  <%# end %>  
</div> -->



<!-- Real email capture below -->

<h2>The way couples connect with other couples</h2>
<div class="splash">
  <%= form_for(@email) do |f| %>
    <div>
      <%= f.label :email do %>
        <%= f.text_field :email , autofocus: true, placeholder: "Enter your email to get started!" %>
      <% end %>
      <%= f.submit 'Go!', :class => "button" %>
    </div>
  <% end %>  
</div>

app/views/home/thanks.html.erb
<div class="thanks">
  <h2>Checkout what we have been up too!</h2>
  <iframe width="853" height="480" src="http://www.youtube.com/embed/Ggw5RUE5CR8" frameborder="2"></iframe>
  <p>Stay tuned for updates!</p>
  <span>Follow us on:<span><h5><%= link_to 'Twitter', 'http://twitter.com/cupplehub' %><h5>
</div>