config/routes.rb
CuppleHub::Application.routes.draw do


  resources :emails, :only => 'create'

  match "/thanks", to: 'home#thanks', as: 'thanks'
  get "profile/show"

  # match "/welcome", to: 'home#splash', as: 'welcome'
  # match "/profile", to: 'home#profile', as: 'profile'
  # get "front/index"
  # get 'home/get_couple'
  # get "modal/index"
  # get "home/modal1"

  resources :outings
  match "/questions", to: 'home#show', as: 'questions'

  devise_for :couples
  resources :couples do
    resources :user_likes
  end

  root to: 'home#splash'
end

app/views/layouts/_header.html.erb
<header class="navbar-inverse navbar-fixed-top">
  <nav class="navbar-inner custom-navbar">
    <div class="container">
      <%= render 'layouts/navigation' %>
    </div>
  </nav>
</header>

</style>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to image_tag("newcupplelogomini.svg", :class=>'minilogo', :style => 'height: 45px; position:relitive;bottom:30px;'), root_path, :class => 'brand' %>
<ul class="nav" style="float:right;">
  <% if couple_signed_in? %>
    <li>
    <%= link_to('Logout', destroy_couple_session_path, :method=>'delete') %>
    </li>
  <% else %>
    <li>
    <%= link_to('Login', new_couple_session_path)  %>
    </li>
  <% end %>
  <% if couple_signed_in? %>
    <li>
    <%= link_to('Edit account', edit_couple_registration_path) %>
    </li>
  <% else %>
<!--    <li>
    <%= link_to('Sign up', new_couple_registration_path)  %>
    </li>
-->
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "CuppleHub" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-42362611-1', 'cupplehub.co');
      ga('send', 'pageview');
    </script>
  </head>
  <% if params[:action] == 'splash' || (params[:controller] == 'home' && params[:action] == 'show') %>
      <body class="splash" >
    <% elsif params[:action] == 'show' && params[:controller] == 'profile' %>
      <body class="proshow" >
    <% else  %>
      <body>
    <% end %>
      <%= render 'layouts/header' %>
      <div id="main" role="main">
        <div class="container">
          <div>
             <div class="row">
              <div class="span12">
                <%= render 'layouts/messages' %>
                <%= yield %>
              </div>
            </div>
            <footer>
            </footer>
          </div>
        </div> <!--! end of .container -->
      </div> <!--! end of #main -->
    </body>

</html>

app/views/layouts/onepage.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>CuppleHub - The way for couples to connect with other couples!</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <!-- styles -->
  <link href="/css/bootstrap.css" rel="stylesheet" />
  <link href="/css/bootstrap-responsive.css" rel="stylesheet" />
  <link href="css/prettyPhoto.css" rel="stylesheet" />
  <link href="/css/animate.css" rel="stylesheet" />
  <link href="/css/style.css" rel="stylesheet" />
  <link href="/color/default.css" rel="stylesheet" />
  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
      <![endif]-->
  <!-- Fav and touch icons -->
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="ico/apple-touch-icon-144-precomposed.png" />
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="ico/apple-touch-icon-114-precomposed.png" />
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="ico/apple-touch-icon-72-precomposed.png" />
  <link rel="apple-touch-icon-precomposed" href="ico/apple-touch-icon-57-precomposed.png" />
  <link rel="shortcut icon" href="ico/favicon.ico" />
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "CuppleHub" %></title>
  <meta name="description" content="">
  <meta name="author" content="">
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield(:head) %>
</head>
<body>
<header>
<!-- start top -->
<div id="topnav" class="navbar navbar-fixed-top default">
  <div class="navbar-inner">
    <div class="container">
      <div class="logo">
        <a href="index.html">
        <!-- <img src="/img/logo.png" alt="" /> -->
        </a>
      </div>
      <div class="navigation">
        <nav>
        <ul class="nav pull-right">
          <li class="current"><a href="#intro">Home</a></li>
          <li><a href="#about">How it works?</a></li>
          <li><a href="#services">About Us</a></li>
          <li><a href="#works">Sign up</a></li>
          <li><a href="#contact">Contact</a></li>
        </ul>
        </nav>
      </div>
      <!--/.nav-collapse -->
    </div>
  </div>
</div>
<!-- end top -->
</header>

<%= yield %>

<footer>
<div class="verybottom">
  <div class="container">
    <div class="row">
      <div class="span12">
        <div class="aligncenter">
          <div class="logo">
            <a class="brand" href="index.html">
            <!-- <img src="/img/logo.png" alt="" /> -->
            </a>
          </div>
          <p>
             &copy; CuppleHub 2013 - All right reserved
          </p>
        </div>
      </div>
    </div>
  </div>
</div>
</footer>
<a href="#" class="scrollup"><i class="icon-chevron-up icon-square icon-48 active"></i></a>
<!-- javascript -->
<script src="/js/jquery.min.js"></script>
<script src="/js/jquery.easing.js"></script>
<script src="/js/bootstrap.js"></script>
<script src="/js/parallax/jquery.parallax-1.1.3.js"></script>
<script src="/js/nagging-menu.js"></script>
<script src="/js/jquery.nav.js"></script>
<script src="/js/prettyPhoto/jquery.prettyPhoto.js"></script>
<script src="/js/portfolio/jquery.quicksand.js"></script>
<script src="/js/portfolio/setting.js"></script>
<script src="/js/hover/jquery-hover-effect.js"></script>
<script src="/js/jquery.scrollTo.js"></script>
<script src="/js/twitter/jquery.tweet.js"></script>
<script src="/js/twitter/function.js"></script>
<script src="/js/animate.js"></script>
<script src="/js/custom.js"></script>
</body>
</html>